### ISSUE TITLE
Segmentation fault on GC exit (libQt 5.6.0)

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1993]
After upgrade Qt to version 5.6 GoldenCheetah always Segmentation fault on application exit.

p.s. GC always full rebuild on clean system after each update in system, include Qt update.  

```
(gdb) run
Starting program: /usr/bin/GoldenCheetah 
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.23-3.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Detaching after fork from child process 18897.
Detaching after fork from child process 18898.
Detaching after fork from child process 18899.
[New Thread 0x7fffe1868700 (LWP 18900)]
[New Thread 0x7fffd6bcd700 (LWP 18901)]
[New Thread 0x7fffcdb67700 (LWP 18902)]
[New Thread 0x7fffc4558700 (LWP 18903)]
[New Thread 0x7fff83842700 (LWP 18904)]
[New Thread 0x7fff83041700 (LWP 18905)]
[New Thread 0x7fff82440700 (LWP 18906)]
[Thread 0x7fff82440700 (LWP 18906) exited]

Thread 3 "QDBusConnection" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd6bcd700 (LWP 18901)]
0x00007ffff1fef377 in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib64/libQt5Core.so.5

(gdb) bt
#0  0x00007ffff1fef377 in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () at /usr/lib64/libQt5Core.so.5
#1  0x00007fffeb719ff8 in  () at /usr/lib64/libQt5DBus.so.5
#2  0x00007fffeb70b896 in  () at /usr/lib64/libQt5DBus.so.5
#3  0x00007ffff1dfcb29 in  () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff18cb454 in start_thread () at /lib64/libpthread.so.0
#5  0x00007ffff0d6c3fd in clone () at /lib64/libc.so.6

```

**Comment by MaksVasilev** [comment]
This a Qt bug: https://bugreports.qt.io/browse/QTBUG-52988
