### ISSUE TITLE
Goldencheetah Crashing when trying to save activity

### ISSUE THREAD

**Issue by navyjosh** [GoldenCheetah/GoldenCheetah#4014]
OS: Ubuntu 21.04
Version: GoldenCheetah_v3.6-DEV compiled from source with debug flag

GoldenCheetah crashes when trying to save activity.
I tried importing the unfinished activity and saving again, the issue is the same.
I tried creating a new activity and it reproduces the same error.

I also tried running GoldenCheetah v3.5 from ubuntu ppa and experienced the same issue when trying to save that activity after importing the unfinished activity from ~/.goldencheetah/Josh/tempActivities

Attached is a zip file containing the activity I am trying to save.

I edited this post to include debug symbols in the stack trace.

Stacktrace:

```
#0  0x000055555586475e in DataOverviewItem::itemPaint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*) (this=0x55555a331150, painter=0x7fffffffb680) at Charts/OverviewItems.cpp:2791
#1  0x0000555555855f4e in ChartSpaceItem::paint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*) (this=0x55555a331150, painter=0x7fffffffb680, opt=0x555559547a28, widget=0x555559bacf70) at Gui/ChartSpace.cpp:362
#2  0x00007ffff77b299b in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff77c7bb7 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff77c8740 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff77c8d72 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff77edd82 in QGraphicsView::paintEvent(QPaintEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff74bc5de in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff756ab32 in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007fffee4cd52b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff7479772 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fffee4cd7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff74b453a in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff74b4d62 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff74b5a72 in QWidgetPrivate::paintOnScreen(QRegion const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff74d98ac in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff7479783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fffee4cd7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fffeec34ee1 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#19 0x00007fffeec08e2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#20 0x00007fffe19f3a6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#21 0x00007fffe9d358eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007fffe9d88d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007fffe9d33023 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007fffee527271 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00005555558adb94 in GenericChart::finaliseChart() (this=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h:121
#26 0x0000555555850f1f in ChartSpace::rideSelected(RideItem*) (this=0x555559babf90, item=0x55555bab7910) at Gui/ChartSpace.cpp:153
#27 0x00007fffee505600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00005555560899d6 in GcWindow::rideItemChanged(RideItem*) (this=<optimized out>, _t1=<optimized out>) at moc_GoldenCheetah.cpp:516
#29 0x000055555608bdeb in GcWindow::qt_metacall(QMetaObject::Call, int, void**) (this=this@entry=0x555559ba23d0, _c=_c@entry=QMetaObject::WriteProperty, _id=4, _a=_a@entry=0x7fffffffc740) at moc_GoldenCheetah.cpp:474
#30 0x000055555608be79 in GcChartWindow::qt_metacall(QMetaObject::Call, int, void**) (this=this@entry=0x555559ba23d0, _c=_c@entry=QMetaObject::WriteProperty, _id=<optimized out>, _a=_a@entry=0x7fffffffc740)
    at moc_GoldenCheetah.cpp:700
#31 0x0000555556069bec in OverviewWindow::qt_metacall(QMetaObject::Call, int, void**) (this=0x555559ba23d0, _c=QMetaObject::WriteProperty, _id=<optimized out>, _a=0x7fffffffc740) at moc_Overview.cpp:155
#32 0x00007fffee4db7cc in QMetaProperty::write(QObject*, QVariant const&) const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fffee504236 in QObject::setProperty(char const*, QVariant const&) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x0000555555e28ce9 in Perspective::tabSelected(int, bool) (this=0x555559b0c0f0, index=0, forride=<optimized out>) at Gui/Perspective.cpp:443
#35 0x0000555555e2a60b in Perspective::rideSelected() (this=0x555559b0c0f0) at Gui/Perspective.cpp:366
#36 0x00007fffee505600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00005555560899d6 in GcWindow::rideItemChanged(RideItem*) (this=<optimized out>, _t1=<optimized out>) at moc_GoldenCheetah.cpp:516
#38 0x000055555608bdeb in GcWindow::qt_metacall(QMetaObject::Call, int, void**) (this=this@entry=0x555559b0c0f0, _c=_c@entry=QMetaObject::WriteProperty, _id=4, _a=_a@entry=0x7fffffffcb30) at moc_GoldenCheetah.cpp:474
#39 0x00005555560ebb59 in Perspective::qt_metacall(QMetaObject::Call, int, void**) (this=0x555559b0c0f0, _c=QMetaObject::WriteProperty, _id=<optimized out>, _a=0x7fffffffcb30) at moc_Perspective.cpp:349
#40 0x00007fffee4db7cc in QMetaProperty::write(QObject*, QVariant const&) const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fffee504236 in QObject::setProperty(char const*, QVariant const&) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x0000555555db04a3 in AnalysisView::setRide(RideItem*) (this=<optimized out>, ride=<optimized out>) at Gui/Views.cpp:102
#43 0x0000555555da382d in AthleteTab::setRide(RideItem*) (this=0x555556f92320, ride=0x55555bab7910) at Gui/AthleteTab.cpp:156
#44 0x0000555555da3c45 in AthleteTab::rideSelected(RideItem*) (this=0x555556f92320) at Gui/AthleteTab.cpp:200
#45 0x00007fffee505600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#46 0x00005555560a8346 in Context::rideSelected(RideItem*) (this=<optimized out>, _t1=<optimized out>) at moc_Context.cpp:1384
#47 0x0000555555b53386 in Context::notifyRideSelected(RideItem*) (x=<optimized out>, this=<optimized out>) at Core/Context.h:217
#48 RideCache::addRide(QString, bool, bool, bool, bool) (this=0x555557582460, name=..., dosignal=<optimized out>, select=<optimized out>, useTempActivities=<optimized out>, planned=<optimized out>) at Core/RideCache.cpp:319
#49 0x0000555555ae3269 in Athlete::addRide(QString, bool, bool, bool, bool) (this=this@entry=0x5555574e1c10, name=..., dosignal=dosignal@entry=true, select=select@entry=true, useTempActivities=useTempActivities@entry=true, planned=planned@entry=false) at Core/Athlete.cpp:282
#50 0x0000555555ddc43b in RideImportWizard::abortClicked() (this=0x55555baa58c0) at Gui/RideImportWizard.cpp:1106
#51 0x00007fffee505600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007ffff756f876 in QAbstractButton::clicked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007ffff756fafe in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007ffff7571bd4 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007ffff7571df5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007ffff74bc5de in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007ffff7479783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007ffff7480e5b in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007fffee4cd7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00007ffff747fe77 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007ffff74d6370 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007ffff74d9615 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007ffff7479783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007fffee4cd7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#65 0x00007fffeec33b13 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#66 0x00007fffeec08e2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#67 0x00007fffe19f3a6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#68 0x00007fffe9d358eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#69 0x00007fffe9d88d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#70 0x00007fffe9d33023 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#71 0x00007fffee527204 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#72 0x00007fffee4cc11b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#73 0x00007fffee4d4604 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#74 0x0000555555790652 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at Core/main.cpp:796

```

Linux Version:

```
$ uname -a
Linux jks-desktop 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

[2021_08_18_15_38_48.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/7033944/2021_08_18_15_38_48.zip)

**Comment by amtriathlon** [comment]
In this thread I indicated other user about how to get a stack trace to debug a crash, that is the information is what we need: https://groups.google.com/g/golden-cheetah-users/c/Xed5ppEmXSw/m/-UPWcLn4AAAJ

**Comment by navyjosh** [comment]
> In this thread I indicated other user about how to get a stack trace to debug a crash, that is the information is what we need: https://groups.google.com/g/golden-cheetah-users/c/Xed5ppEmXSw/m/-UPWcLn4AAAJ

Here is the stacktrace

#0  0x00007fc1705de044 in QColor::operator=(QColor const&) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00005560817102e1 in  ()
#2  0x0000556081712288 in  ()
#3  0x00007fc16fce9600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x0000556081cc4da6 in  ()
#5  0x0000556081cc659b in  ()
#6  0x0000556081cc6619 in  ()
#7  0x0000556081cb9faa in  ()
#8  0x00007fc16fcbf7cc in QMetaProperty::write(QObject*, QVariant const&) const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fc16fce8236 in QObject::setProperty(char const*, QVariant const&) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00005560817cb212 in  ()
#11 0x00005560817d4fa2 in  ()
#12 0x00005560817d5c6a in  ()
#13 0x0000556081b184e2 in  ()
#14 0x00007fc16fce9600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x0000556081cdd226 in  ()
#16 0x0000556081944c53 in  ()
#17 0x000055608190ff3c in  ()
#18 0x0000556081b3ad44 in  ()
#19 0x00007fc16fce9600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007fc173a4b876 in QAbstractButton::clicked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fc173a4bafe in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007fc173a4dbd4 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fc173a4ddf5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fc1739985de in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fc173955783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fc17395ce5b in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fc16fcb17ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007fc17395be77 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007fc1739b2370 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007fc1739b5615 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007fc173955783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007fc16fcb17ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fc1703f0b13 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#34 0x00007fc1703c5e2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#35 0x00007fc16885ea6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#36 0x00007fc16d8638eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fc16d8b6d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fc16d861023 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007fc16fd0b204 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007fc16fcb011b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fc16fcb8604 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x000055608168576b in main ()

**Comment by navyjosh** [comment]
> In this thread I indicated other user about how to get a stack trace to debug a crash, that is the information is what we need: https://groups.google.com/g/golden-cheetah-users/c/Xed5ppEmXSw/m/-UPWcLn4AAAJ

I am new to debugging code like this.  After some asking around I have realized that the stack trace above is not very helpful because it does not include debug symbols.

I have therefore compiled GC with debug enabled and performed a new stack trace.  See below.

```#0  0x000055555586475e in DataOverviewItem::itemPaint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*) (this=0x55555a331150, painter=0x7fffffffb680) at Charts/OverviewItems.cpp:2791
#1  0x0000555555855f4e in ChartSpaceItem::paint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*) (this=0x55555a331150, painter=0x7fffffffb680, opt=0x555559547a28, widget=0x555559bacf70) at Gui/ChartSpace.cpp:362
#2  0x00007ffff77b299b in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff77c7bb7 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff77c8740 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff77c8d72 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff77edd82 in QGraphicsView::paintEvent(QPaintEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff74bc5de in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff756ab32 in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007fffee4cd52b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff7479772 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fffee4cd7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff74b453a in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff74b4d62 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff74b5a72 in QWidgetPrivate::paintOnScreen(QRegion const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff74d98ac in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff7479783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fffee4cd7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fffeec34ee1 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#19 0x00007fffeec08e2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#20 0x00007fffe19f3a6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#21 0x00007fffe9d358eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007fffe9d88d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007fffe9d33023 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007fffee527271 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00005555558adb94 in GenericChart::finaliseChart() (this=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h:121
#26 0x0000555555850f1f in ChartSpace::rideSelected(RideItem*) (this=0x555559babf90, item=0x55555bab7910) at Gui/ChartSpace.cpp:153
#27 0x00007fffee505600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00005555560899d6 in GcWindow::rideItemChanged(RideItem*) (this=<optimized out>, _t1=<optimized out>) at moc_GoldenCheetah.cpp:516
#29 0x000055555608bdeb in GcWindow::qt_metacall(QMetaObject::Call, int, void**) (this=this@entry=0x555559ba23d0, _c=_c@entry=QMetaObject::WriteProperty, _id=4, _a=_a@entry=0x7fffffffc740) at moc_GoldenCheetah.cpp:474
#30 0x000055555608be79 in GcChartWindow::qt_metacall(QMetaObject::Call, int, void**) (this=this@entry=0x555559ba23d0, _c=_c@entry=QMetaObject::WriteProperty, _id=<optimized out>, _a=_a@entry=0x7fffffffc740)
    at moc_GoldenCheetah.cpp:700
#31 0x0000555556069bec in OverviewWindow::qt_metacall(QMetaObject::Call, int, void**) (this=0x555559ba23d0, _c=QMetaObject::WriteProperty, _id=<optimized out>, _a=0x7fffffffc740) at moc_Overview.cpp:155
#32 0x00007fffee4db7cc in QMetaProperty::write(QObject*, QVariant const&) const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fffee504236 in QObject::setProperty(char const*, QVariant const&) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x0000555555e28ce9 in Perspective::tabSelected(int, bool) (this=0x555559b0c0f0, index=0, forride=<optimized out>) at Gui/Perspective.cpp:443
#35 0x0000555555e2a60b in Perspective::rideSelected() (this=0x555559b0c0f0) at Gui/Perspective.cpp:366
#36 0x00007fffee505600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00005555560899d6 in GcWindow::rideItemChanged(RideItem*) (this=<optimized out>, _t1=<optimized out>) at moc_GoldenCheetah.cpp:516
#38 0x000055555608bdeb in GcWindow::qt_metacall(QMetaObject::Call, int, void**) (this=this@entry=0x555559b0c0f0, _c=_c@entry=QMetaObject::WriteProperty, _id=4, _a=_a@entry=0x7fffffffcb30) at moc_GoldenCheetah.cpp:474
#39 0x00005555560ebb59 in Perspective::qt_metacall(QMetaObject::Call, int, void**) (this=0x555559b0c0f0, _c=QMetaObject::WriteProperty, _id=<optimized out>, _a=0x7fffffffcb30) at moc_Perspective.cpp:349
#40 0x00007fffee4db7cc in QMetaProperty::write(QObject*, QVariant const&) const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fffee504236 in QObject::setProperty(char const*, QVariant const&) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x0000555555db04a3 in AnalysisView::setRide(RideItem*) (this=<optimized out>, ride=<optimized out>) at Gui/Views.cpp:102
#43 0x0000555555da382d in AthleteTab::setRide(RideItem*) (this=0x555556f92320, ride=0x55555bab7910) at Gui/AthleteTab.cpp:156
#44 0x0000555555da3c45 in AthleteTab::rideSelected(RideItem*) (this=0x555556f92320) at Gui/AthleteTab.cpp:200
#45 0x00007fffee505600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#46 0x00005555560a8346 in Context::rideSelected(RideItem*) (this=<optimized out>, _t1=<optimized out>) at moc_Context.cpp:1384
#47 0x0000555555b53386 in Context::notifyRideSelected(RideItem*) (x=<optimized out>, this=<optimized out>) at Core/Context.h:217
#48 RideCache::addRide(QString, bool, bool, bool, bool) (this=0x555557582460, name=..., dosignal=<optimized out>, select=<optimized out>, useTempActivities=<optimized out>, planned=<optimized out>) at Core/RideCache.cpp:319
#49 0x0000555555ae3269 in Athlete::addRide(QString, bool, bool, bool, bool) (this=this@entry=0x5555574e1c10, name=..., dosignal=dosignal@entry=true, select=select@entry=true, useTempActivities=useTempActivities@entry=true, planned=planned@entry=false) at Core/Athlete.cpp:282
#50 0x0000555555ddc43b in RideImportWizard::abortClicked() (this=0x55555baa58c0) at Gui/RideImportWizard.cpp:1106
#51 0x00007fffee505600 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007ffff756f876 in QAbstractButton::clicked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007ffff756fafe in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007ffff7571bd4 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007ffff7571df5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007ffff74bc5de in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007ffff7479783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007ffff7480e5b in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007fffee4cd7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00007ffff747fe77 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007ffff74d6370 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007ffff74d9615 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007ffff7479783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007fffee4cd7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#65 0x00007fffeec33b13 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#66 0x00007fffeec08e2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#67 0x00007fffe19f3a6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#68 0x00007fffe9d358eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#69 0x00007fffe9d88d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#70 0x00007fffe9d33023 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#71 0x00007fffee527204 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#72 0x00007fffee4cc11b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#73 0x00007fffee4d4604 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#74 0x0000555555790652 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at Core/main.cpp:796```

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/29485aa32740ab4435ec0fc528de7413a7e38d17, checkout current master or wait for the next build.

**Comment by navyjosh** [comment]
Thank you.  I cherry picked this commit and solved the issue.  I could not check out current master to build because my local bison version is 3.7.5 and would not compile with current master.  I had to merge with another branch to provide a fix for compiling with newer versions of bison.
